-- Example gold layer transformation for customer summary
-- This would be auto-generated by the metadata framework

SELECT
  customer_id AS id,
  customer_first_name AS first_name,
  customer_last_name AS last_name,
  customer_email AS email,
  customer_created_at AS created_at,
  COUNT(orders.order_id) AS total_orders
FROM {{ ref('customer_dim') }}
LEFT JOIN {{ ref('order_fact') }} 
  ON customer_dim.customer_id = order_fact.customer_key
GROUP BY customer_id, customer_first_name, customer_last_name, 
         customer_email, customer_created_at