-- Example silver layer transformation for customers
-- This would be auto-generated by the metadata framework

SELECT
  id AS customer_id,
  first_name AS customer_first_name,
  last_name AS customer_last_name,
  email AS customer_email,
  created_at AS customer_created_at
FROM {{ source('raw_data', 'customers') }}
WHERE email IS NOT NULL
  AND LENGTH(first_name) > 0