-- Example silver layer transformation for orders
-- This would be auto-generated by the metadata framework

SELECT
  id AS order_id,
  customer_id AS customer_key,
  product_id AS product_key,
  quantity AS order_quantity,
  price AS unit_price,
  order_date AS order_timestamp
FROM {{ source('raw_data', 'orders') }}
WHERE quantity > 0
  AND price > 0